import type { AdminRejectReasonCode } from "@/lib/app-enums"

/**
 * Libellés UI partagés (FR). Centraliser ici pour uniformiser puis brancher i18n / types stricts.
 */
export const AppLabel = {
  common: {
    save: "Enregistrer",
    cancel: "Annuler",
    close: "Fermer",
    add: "Ajouter",
    detail: "Détail",
    list: "Liste",
  },
  absence: {
    sheetTitle: "Absences",
    sheetSubtitle: "Aligné sur la page Absences.",
    newRequest: "Nouvelle demande",
    emptyList: "Aucune demande.",
    countersCpShort: "Congés payés",
    countersTtShort: "Télétravail",
    countersOtherShort: "Absences & maladie",
    countersCpUsedHint: "utilisés sur le solde",
    countersTtBalanceHint: "sur plafond TT",
    countersOtherHint: "hors CP (j. ouvrés)",
    pageRequestsTitle: "Mes demandes",
    addButton: "Ajouter",
    filterAll: "Toutes",
    filterPending: "En attente",
    filterApproved: "Approuvées",
    filterRejected: "Refusées",
    requestsEmpty: "Aucune demande",
    requestFormTitle: "Demande d'absence",
    requestFormSubtitle:
      "Remplissez le formulaire. La demande est envoyée à votre référent pour validation.",
    fieldType: "Type d'absence",
    typePlaceholder: "Sélectionner un type",
    fieldPeriod: "Période",
    halfDay: "Demi-journée",
    durationFromBalance: "Durée déduite du solde",
    fieldMotif: "Motif (optionnel)",
    motifPlaceholder: "Précisez le motif de votre demande…",
    validationProcess: "Processus de validation",
    deleteRequest: "Supprimer la demande",
    deleteOnlyPending: "Suppression réservée aux demandes en attente",
    toastRequestSavedTitle: "Demande enregistrée",
    toastRequestSavedDesc: "Votre demande a été transmise pour validation.",
    toastRequestDeletedTitle: "Demande retirée",
    toastRequestDeletedDesc: "La demande en attente a été supprimée.",
    typeCongesPayes: "Congés payés",
    typeTeletravail: "Télétravail",
    typeMaladie: "Maladie",
    typeSansSolde: "Sans solde",
  },
  timesheet: {
    dayPanelWeekProgress: "Semaine en cours",
    dayPanelTotalDay: "Total du jour",
    pastWeekBanner: "Semaine passée — modifications encore possibles",
    noActivityDay: "Aucune activité pour cette journée",
    addActivity: "Ajouter une activité",
    saveDayToastTitle: "Journée enregistrée",
    saveDayToastDesc: "Vos saisies sont enregistrées. Vous pouvez rouvrir ce jour pour modifier.",
  },
  admin: {
    tabPending: "Demandes en attente",
    tabNotifications: "Notifications",
    tabJournal: "Journal",
    pendingBadgeAria: "Nombre de demandes en attente",
    notificationsUnreadAria: "Notifications non lues",
    emptyPending: "Aucune demande en attente",
    openDetail: "Ouvrir le détail",
    approve: "Approuver",
    reject: "Refuser",
    panelEmployeeSubtitle: "Demande à traiter",
    panelFieldType: "Type",
    panelFieldPeriod: "Période",
    panelFieldDuration: "Durée",
    panelLeaveBalance: "Solde congés disponible",
    panelLeaveBalanceValue: "18 jours",
    timesheetRequestLabel: "Feuille de temps",
    rejectDialogTitle: "Confirmer le refus",
    rejectMotifLabel: "Motif de refus",
    rejectMotifRequired: "Sélectionner un motif",
    rejectCommentLabel: "Commentaire",
    rejectCommentOptional: "(optionnel)",
    rejectCommentPlaceholder: "Précisez la raison du refus si nécessaire…",
    rejectSubmit: "Refuser la demande",
    toastApprovedTitle: "Demande approuvée",
    toastApprovedDesc: "La décision a été enregistrée. L’employé peut en être informé.",
    toastRejectedTitle: "Demande refusée",
    toastRejectedDesc: "Le refus et le motif ont été enregistrés.",
    changelogValidation: "Validation",
    changelogRefus: "Refus",
    changelogConfig: "Configuration",
    changelogCompte: "Compte",
    priorityUrgent: "Urgent",
  },
  support: {
    overviewTitle: "Vue d'ensemble",
    overviewPopoverTitle: "Vue d'ensemble équipe",
    overviewStatTeam: "Équipe",
    overviewStatCollabShort: "collab.",
    overviewStatComplete: "Complets",
    overviewStatLate: "En retard",
    overviewStatHours: "Heures",
    overviewTooltipCollaborators: "Collaborateurs",
    overviewTooltipHoursLogged: "Heures saisies",
    overviewTooltipCompletionRate: "Taux de complétion",
    overviewTooltipComplete: "Complets",
    overviewTooltipLate: "En retard",
    overviewTooltipIncomplete: "Incomplets",
    overviewCardLateFooter: "Alertes « en retard » (suivi mois)",
    periodAnalyzedTitle: "Période analysée",
    periodResetScope: "Réinitialiser portée",
    periodScopeTitle: "Portée de la liste",
    periodScopeAll: "Tous les mois",
    periodScopeThroughCurrent: "Jusqu'au mois courant (inclus)",
    periodScopePastOnly: "Mois passés uniquement",
    periodPickMonth: "Choisir un mois",
    periodEmptyScope: "Aucun mois dans cette portée.",
    periodCurrentTag: "courant",
    exportGlobalCsv: "Export global CSV",
    exportGlobalCsvShort: "CSV",
    tabMonthly: "Vue mensuelle",
    tabByUser: "Par collaborateur",
    searchPlaceholder: "Rechercher…",
    filtersButton: "Filtres",
    filtersTitle: "Filtres",
    filtersClearAll: "Effacer tout",
    filtersApply: "Appliquer",
    filterStatusLabel: "Statut",
    filterStatusAll: "Tous",
    filterStatusComplete: "Complets",
    filterStatusIncomplete: "Incomplets",
    filterStatusLate: "En retard",
    filterDeptLabel: "Département",
    filterDeptAll: "Tous les départements",
    listColCollaborator: "Collaborateur",
    listColProjects: "Projets",
    listColLeave: "Congés",
    listColHoursMonth: "Heures / mois",
    listColStatus: "Statut",
    listEmptyFilters: "Aucun collaborateur ne correspond aux filtres",
    congesPopoverTitle: "Soldes & absences",
    statCpUsed: "CP utilisés",
    statCpRemaining: "CP restants",
    statTtUsed: "TT utilisés",
    statTtRemaining: "TT restants",
    statAbsenceOther: "Absences & maladie",
    exportCsv: "Exporter CSV",
    viewDetail: "Voir le détail",
    monthCurrentBadge: "Mois en cours",
    monthPhaseArchive: "Archivé",
    monthPhaseComplete: "Complet",
    monthPhaseInProgress: "En cours",
    monthCompleteSummary: "collaborateurs complets",
    exportShort: "Export",
    tableColCollaborator: "Collaborateur",
    tableColTotal: "Total",
    tableColStatus: "Statut",
    tableActionsAria: "Actions ligne",
    legendTitle: "Légende (même code couleur que le détail Pointage) :",
    legendDayFilled: "Jour saisi",
    legendPartial: "Partiel",
    legendEmpty: "Non saisi",
    legendAbsent: "Absence",
    statusComplet: "Complet",
    statusIncomplet: "Incomplet",
    statusEnRetard: "En retard",
    panelTabWeeks: "Semaines",
    panelTabProfile: "Profil",
    panelExportCsvAria: "Exporter CSV du collaborateur",
    panelPeriodFallback: "Période",
    panelWeekDetailTitle: "Détail par semaine",
    panelWeekNoWorkdaysInMonth:
      "Aucun jour ouvré de cette semaine ISO dans le mois sélectionné ({month}).",
    panelWeekBadgeAbsent: "Absence",
    panelLinkFullProfile: "Voir le profil complet de",
    panelResourcesCardTitle: "Ressources & soldes",
    panelProjectsActive: "Projets actifs",
    panelProjectsOngoing: "en cours",
    panelProjectsMore: "autres",
    panelCpRemaining: "CP restants",
    panelTtRemaining: "TT restants",
    panelHoursByProject: "Heures par projet",
    panelHoursByProjectSubtitle: "Période analysée :",
    panelNoSplitForMonth: "Pas de répartition pour ce mois.",
    panelTotalForMonth: "Total",
    panelLeaveSection: "Congés & absences",
    panelLeaveDay: "jour",
    panelLeaveDays: "jours",
    panelNoAbsencesTitle: "Aucune absence enregistrée",
    panelNoAbsencesDesc:
      "Aucune période de congé ou d'absence n'est renseignée pour ce collaborateur sur la maquette.",
    stickHoursLogged: "h saisies",
    stickPartial: "saisie partielle",
    stickAbsent: "absence",
    stickEmpty: "non saisi",
    toastExportTitle: "Export généré",
    toastExportDesc: "Le fichier CSV « {file} » a été téléchargé.",
    unassignedProject: "Non affecté",
  },
} as const

/** Libellés FR des motifs de refus (codes `AdminRejectReasonCode`). */
export const adminRejectReasonLabels: Record<AdminRejectReasonCode, string> = {
  solde_insuffisant: "Solde insuffisant",
  periode_non_autorisee: "Période non autorisée",
  conflit_equipe: "Conflit d'équipe",
  delai_prevenance: "Délai de prévenance non respecté",
  doublon: "Doublon de demande",
  autre: "Autre",
}
